import os

class Config:
    MODEL_PATH = os.path.join(os.path.dirname(__file__), 'models')
    THRESHOLD = 0.4
    
    VIOLATION_TYPES = {
        "misleading": "Inaccurate or misleading information",
        "dangerous": "Encouraging dangerous workouts",
        "abusive": "Abusive or harassing content",
        "unsafe": "Promotion of unsafe products or methods",
        "scam": "Scam or fraud"
    }
    
    VIOLATION_KEYWORDS = {
        "dangerous": [
            "no need to warm up",
            "overdose",
            "double the weights",
            "train until fainting",
            "no rest in between",
            "train continuously",
            "back pain is normal",
            "take painkillers and train",
            "don’t need to care",
            "triple the dosage",
            "push past the pain",
            "ignore medical advice",
            "train until you collapse",
            "pain is weakness leaving the body",
            "excessive repetitions",
            "sweat equals fat loss",
            "no need for proper form",
            "overdose",
            "fainting",
            "collapse",
            "painkillers",
            "excessive",
            "strain",
            "injury",
            "overtrain",
            "ignore",
            "triple",
            "double",
            "reckless",
            "fatigue",
            "misform",
            "improper",
            "unrest",
            "burnout",
            "overload",
            "risk",
            "push"
        ],
        "unsafe": [
            "steroid",
            "banned",
            "stimulants",
            "unapproved",
            "illegal",
            "enhancers",
            "hormones",
            "toxins",
            "unregulated",
            "counterfeit",
            "addictive",
            "hazardous",
            "pills",
            "substances",
            "unverified",
            "blackmarket",
            "contaminants",
            "unlabeled",
            "adulterated",
            "illicit"
        ],
        "scam": [
            "guaranteed 100%",
            "money back",
            "instant results",
            "only in 1 week",
            "no need to train",
            "too good to be true",
            "limited time offer",
            "secret formula",
            "get ripped overnight",
            "lose 10kg in 3 days",
            "no effort required",
            "exclusive deal",
            "transform instantly",
            "act now"
        ],
        "misleading": [
            "clinically proven",
            "doctor recommended",
            "scientific breakthrough",
            "miracle cure",
            "as seen on TV",
            "used by celebrities",
            "revolutionary technique",
            "perfect for everyone",
            "zero side effects",
            "guaranteed satisfaction",
            "proven results",
            "trusted by experts",
            "one-size-fits-all",
            "100% natural",
            "works instantly",
            "risk-free",
            "no effort needed",
            "overnight success",
            "secret formula",
            "once-in-a-lifetime"
        ],
        "abusive": [
            "harassment",
            "insult",
            "threat",
            "bullying",
            "offensive",
            "demeaning",
            "slur",
            "profanity",
            "intimidation",
            "mockery",
            "hate",
            "disrespect",
            "ridicule",
            "abuse",
            "shame",
            "defamation",
            "hostility",
            "aggression",
            "violence",
            "victimization"
        ]
    }
    
    VIOLATION_SEVERITY = {
        "dangerous": 0.9,
        "unsafe": 0.7,
        "scam": 0.6,
        "misleading": 0.5,
        "abusive": 0.6
    }